# Use password auth
auth = "${RPC_AUTH}"
# The listening RPC address of bitcoind, port is usually 8332
daemon_rpc_addr = "${DAEMON_RPC_ADDR}"
# The listening P2P address of bitcoind, port is usually 8333
daemon_p2p_addr = "${DAEMON_P2P_ADDR}"
# Directory where the index should be stored. It should have at least 70GB of free space.
db_dir = "${DB_DIR}"

# bitcoin means mainnet. Don't set to anything else unless you're a developer.
network = "${NETWORK}"

# The address on which electrs should listen. Warning: 0.0.0.0 is probably a bad idea!
electrum_rpc_addr = "${ELECTRUM_RPC_ADDR}"

# How much information about internal workings should electrs print. Increase before reporting a bug.
log_filters = "${LOG_FILTERS}"
