version: "3.9"
services:
  electrs:
    build: 
      context: ./
      args: 
        VERSION: "v0.10.0" #electrs version
    volumes:
      - ./config.toml:/data/.electrs/config.toml #electrs configuration file
      - ./electrs-data:/electrs/data #electrs database
    ports:
      - 50001:50001 #Mainnet RPC

networks:
  default:
    name: bitcoin-nw
    external: true
